export const useUmlaute = true;
export const defaultLanguage = "de-DE";
export const nicerTrashcanNames = true;

export const trashcanNameReplacements: Record<string, string> = {
	Restabfallbehaelter: "⚫️",
	"Gelbe Grossbehaelter": "💛💛",
	"Gelbe Behaelter": "💛",
	Bioabfallbehaelter: "💚",
	Papierbehaelter: "🔵",
	"Weihnachtsbaeume": "🎄",
	"Sperrmuell": "🚚"
};

export const fonts = [
	"PleaseWriteMeASong",
	"monospace",
	"Arial",
	"Arial Black",
	"Bahnschrift",
	"Calibri",
	"Cambria",
	"Cambria Math",
	"Candara",
	"Comic Sans MS",
	"Consolas",
	"Constantia",
	"Corbel",
	"Courier New",
	"Ebrima",
	"Franklin Gothic Medium",
	"Gabriola",
	"Gadugi",
	"Georgia",
	"HoloLens MDL2 Assets",
	"Impact",
	"Ink Free",
	"Javanese Text",
	"Leelawadee UI",
	"Lucida Console",
	"Lucida Sans Unicode",
	"Malgun Gothic",
	"Marlett",
	"Microsoft Himalaya",
	"Microsoft JhengHei",
	"Microsoft New Tai Lue",
	"Microsoft PhagsPa",
	"Microsoft Sans Serif",
	"Microsoft Tai Le",
	"Microsoft YaHei",
	"Microsoft Yi Baiti",
	"MingLiU-ExtB",
	"Mongolian Baiti",
	"MS Gothic",
	"MV Boli",
	"Myanmar Text",
	"Nirmala UI",
	"Palatino Linotype",
	"Segoe MDL2 Assets",
	"Segoe Print",
	"Segoe Script",
	"Segoe UI",
	"Segoe UI Historic",
	"Segoe UI Emoji",
	"Segoe UI Symbol",
	"SimSun",
	"Sitka",
	"Sylfaen",
	"Symbol",
	"Tahoma",
	"Times New Roman",
	"Trebuchet MS",
	"Verdana",
	"Webdings",
	"Wingdings",
	"Yu Gothic",
];
